version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pre build phase - example download dependencies it has been needed"
  build:
    commands:
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "Moving the files that will be upload"
      - mv target/*.war ./ROOT.war
  artifacts:
    files:
      - ROOT.war